### ISSUE TITLE
error when using group chat id

### ISSUE THREAD

**Issue by jeremyj** [Thor77/sensu-telegram-handler#1]
Hello,

I see that the plugin expects the chat id to be `uint` but this is not always the case.
When I use my group chat id which is negative (i.e. -123456) the plugin throws an error.
Can this be fixed somehow?

Thanks

**Comment by jeremyj** [comment]
OK so it seems that the problem is here: https://github.com/sensu/sensu-plugins-go-library/issues/6

**Comment by Archana-B** [comment]
@jeremyj  Even am facing this same issue since chat id is negative. Have you found any solution or workaround for this?

**Comment by jeremyj** [comment]
a merge fixed this https://github.com/sensu/sensu-plugins-go-library/pull/12

**Comment by ichilton** [comment]
Is this working for others? - i'm getting an error trying to use a negative chat id for a group chat:

```
Error: invalid argument "-47xxxxxxx" for "-c, --chatid" flag: strconv.ParseUint: parsing "-47xxxxxxx": invalid syntax
```
