### ISSUE TITLE
working out of the box

### ISSUE THREAD

**Issue by Igors5** [Thor77/sensu-telegram-handler#2]
please change chat_id to int64 type, because it has positive value for private chats and negative value for multiple people chats, also change default message markup from 
```
"**{{.Entity.Name}}/{{.Check.Name}}**: {{.Check.State}}\n`{{.Check.Output}}`"
```
to 
```
"*{{.Entity.Name}}/{{.Check.Name}}*: {{.Check.State}}\n`{{.Check.Output}}`"
```
telegram markup bold is \*text\*, not \*\*text\*\*, and it throws markup error if its \*\*text\*\*

thanks

**Comment by ichilton** [comment]
I'm having the problem with needing a negative value for group chats too - anyone looked at this or got a workaround?
